### ISSUE TITLE
Preview issues with yarn install and yarn develop

### ISSUE THREAD

**Issue by VickyGarnett** [DARIAH-ERIC/dariah-campus#48]
Hi Stefan,

Sorry to bother you, but I have been having some real problems with getting a preview of the DARIAH-Campus site on my Macbook.  Both Toma and I have been trying to fix this over the past week, and while he is able to run it without any problems on his Macbook, I am continuing to get the same errors.  Toma has tried his best to fix this, but he is unable to reproduce the errors I am getting.  I am working in the main DARIAH-Campus repository, in the Master branch.

The steps taken today that have resulted in the same issue are:

Cloned DARIAH-Campus main repository to my Macbook hard drive
Ran 'brew install' and then 'brew upgrade' in Terminal.
Ran 'yarn install' in the DARIAH-Campus folder
Ran 'yarn develop' 
cleared the cache on my browser
once 'yarn develop' finished running, pasted the link into the browser.

While the home page for DARIAH-Campus is previewing without issue, the 'Resources' page keeps showing errors.

I attach screengrabs of the 'Resources' page, and the full output of yarn install and yarn develop from the terminal.

[Terminal Yarn install yarn develop issues 23 Mar 2020.pdf](https://github.com/DARIAH-ERIC/dariah-campus/files/4370206/Terminal.Yarn.install.yarn.develop.issues.23.Mar.2020.pdf)
<img width="1280" alt="Screenshot 2020-03-23 at 15 00 16" src="https://user-images.githubusercontent.com/57193002/77331412-97b3b100-6d18-11ea-94f8-2fd83608264e.png">

If you have any suggestions for how we can fix this, that would be really helpful.  If you need more info, do let me know.

Thanks!

Vicky

**Comment by stefanprobst** [comment]
hi, could you please paste the output of `gatsby info` (or `yarn gatsby info`). thx!

**Comment by stefanprobst** [comment]
also, if you havent't already tried: delete the node modules folder with `rm -rf node_modules` and then run `yarn` again.

**Comment by stefanprobst** [comment]
this might actually be an issue with node 13.10.1 -- not sure how exactly to do this with `brew` but you can try to install `node@12`

**Comment by VickyGarnett** [comment]
> hi, could you please paste the output of `gatsby info` (or `yarn gatsby info`). thx!

This was the output from this:


Last login: Mon Mar 23 14:58:55 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Vickys-MacBook-Pro:~ vickygarnett$ cd
Vickys-MacBook-Pro:~ vickygarnett$ cd /Users/vickygarnett/GitHub\ Development/DARIAH\ Campus/dariah-campus 
Vickys-MacBook-Pro:dariah-campus vickygarnett$ yarn install
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.33s.
Vickys-MacBook-Pro:dariah-campus vickygarnett$ yarn gatsby info
yarn run v1.22.4
$ '/Users/vickygarnett/GitHub Development/DARIAH Campus/dariah-campus/node_modules/.bin/gatsby' info

  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.11.0 - /var/folders/hs/w64nq3_s0zz1stpx9jvq87dw0000gn/T/yarn--1585059961073-0.4194037804249269/node
    Yarn: 1.22.4 - /var/folders/hs/w64nq3_s0zz1stpx9jvq87dw0000gn/T/yarn--1585059961073-0.4194037804249269/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 3.6.4 - /Users/vickygarnett/anaconda3/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 73.0.1
    Safari: 13.0.5
  npmPackages:
    gatsby: 2.13.62 => 2.13.62
    gatsby-image: ^2.2.30 => 2.2.39
    gatsby-plugin-algolia: ^0.3.4 => 0.3.4
    gatsby-plugin-google-analytics: ^2.1.37 => 2.1.37
    gatsby-plugin-manifest: ^2.2.26 => 2.2.40
    gatsby-plugin-mdx: ^1.0.55 => 1.0.69
    gatsby-plugin-netlify: ^2.1.23 => 2.1.31
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.21
    gatsby-plugin-sass: ^2.1.20 => 2.1.27
    gatsby-plugin-sharp: ^2.2.36 => 2.4.4
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2
    gatsby-remark-autolink-headers: ^2.1.16 => 2.1.23
    gatsby-remark-copy-linked-files: ^2.1.28 => 2.1.36
    gatsby-remark-images: ^3.1.28 => 3.1.43
    gatsby-remark-smartypants: ^2.1.14 => 2.1.20
    gatsby-source-filesystem: ^2.1.35 => 2.1.47
    gatsby-transformer-sharp: ^2.3.2 => 2.3.13
    gatsby-transformer-yaml: ^2.2.15 => 2.2.23


✨  Done in 3.12s.
Vickys-MacBook-Pro:dariah-campus vickygarnett$

**Comment by VickyGarnett** [comment]
> also, if you havent't already tried: delete the node modules folder with `rm -rf node_modules` and then run `yarn` again.

Tried this - had the same issue as before...

**Comment by VickyGarnett** [comment]
> this might actually be an issue with node 13.10.1 -- not sure how exactly to do this with `brew` but you can try to install `node@12`

Toma and I tried many different ways to do this, but it requires a bit of work because my computer doesn't seem to want to play.  

We'll try this again tomorrow, and I'll let you know how we got on.

**Comment by stefanprobst** [comment]
thx for the info!
i confirmed locally this is indeed a very weird issue with `node` >=13.10.1 plus `babel` 7.8.3 (not sure whose fault)

in any case, this should be fixed upstream soon -- but in the meantime downgrading node to version 12 (which is the current long-time-support version) should fix this.

sorry you ran into that issue!

**Comment by stefanprobst** [comment]
to install: `brew unlink node` and `brew install node@12`.

**Comment by stefanprobst** [comment]
after that you will probably need to clear your caches again if you get an error something like "failed to build sharp"

**Comment by stefanprobst** [comment]
scratch the above

this should now work (hopefully): `git pull && yarn`

**Comment by VickyGarnett** [comment]
> scratch the above
> 
> this should now work (hopefully): `git pull && yarn`

Um, I don't know what I've done here, but it seems to have made things worse :/

For info - before I did this, I fetched origin again, then ran all the above in Terminal, and then tried yarn install and then develop, and it didn't like it:

(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git pull && yarn
Already up to date.
env: node: No such file or directory
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ cd
(base) Vickys-MacBook-Pro:~ vickygarnett$ cd /Users/vickygarnett/GitHub\ Development/DARIAH\ Campus/dariah-campus 
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ yarn install
env: node: No such file or directory
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ yarn develop
env: node: No such file or directory
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$

**Comment by ttasovac** [comment]
Vicky, this is probably because you don't have node anymore. brew wouldn't let us link the new version yesterday.

I'll look for you on Skype now :) 

--
Belgrade Center for Digital Humanities
http://humanistika.org

**Comment by VickyGarnett** [comment]
Hi Stefan - Toma has been incredibly patient trying to find a solution over the past week or so.  We have managed to downgrade to Node 12 successfully, but still having the same issue with trying to get a preview on a local version.  However, we have also found that this only happens in my Master branch.  I am able to get a functioning preview when using another branch.

While this is OK in the short term, it's obviously not ideal in the longer term.

For info - the nodes_module folder was deleted from my local folder, and replaced with the correct folder when running 'yarn install'.  If you need any more information, please let me know.

Thanks, and again, I'm sorry to keep coming to you with this.

**Comment by stefanprobst** [comment]
sorry to hear this is still an issue (btw node version should not matter anymore)

can you first check that your master branch (i assume we're talking about your fork?) is in sync with upstream?

what does the following print?
```sh
git log --oneline | head -n1
```

**Comment by VickyGarnett** [comment]
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git log --oneline | head -n1
bba98b1 Update about.mdx
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$

**Comment by stefanprobst** [comment]
this is in your master branch? (it's surprising because that commit hash refers to something that's not in upstream master)

**Comment by stefanprobst** [comment]
## sync your master branch with upstream master

0. check that you're in master and that `git status` does not show any uncommitted changes
1. make copy of your current master with `git checkout -b mastercopy` (just in case)
2. change back to master: `git checkout master`
3. we're going to hard reset master `git reset --hard b4cf534`
4. ensure you have correct upstream remote: `git remote -v` shows the DARIAH_ERIC repo as upstream
5. fast-forward to where upstream master's head is: `git pull upstream master`

## clear everything

6. `rm -rf node_modules`
7. `yarn cache clean`
8. `yarn clean`

## let's try now

9. `yarn install`
10. `yarn start`

**Comment by VickyGarnett** [comment]
Hi Stefan,

I got as far as point 5 before things started to look odd.  As you can see, I seem to have some sort of connection to Natasha's stream here, which I'm not sure I should have:
```sh
Last login: Tue Apr  7 10:12:55 on ttys001

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) Vickys-MacBook-Pro:~ vickygarnett$ git status
fatal: not a git repository (or any of the parent directories): .git
(base) Vickys-MacBook-Pro:~ vickygarnett$ cd 
(base) Vickys-MacBook-Pro:~ vickygarnett$ cd /Users/vickygarnett/GitHub\ Development/DARIAH\ Campus/dariah-campus 
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ 
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git checkout -b mastercopy
Switched to a new branch 'mastercopy'
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git reset --hard b4cf534
HEAD is now at b4cf534 Proofreading WS2019 sessions
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git remote -v
github-desktop-n-romanova	https://github.com/n-romanova/dariah-campus.git (fetch)
github-desktop-n-romanova	https://github.com/n-romanova/dariah-campus.git (push)
origin	https://github.com/DARIAH-ERIC/dariah-campus.git (fetch)
origin	https://github.com/DARIAH-ERIC/dariah-campus.git (push)
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git remote -v
github-desktop-n-romanova	https://github.com/n-romanova/dariah-campus.git (fetch)
github-desktop-n-romanova	https://github.com/n-romanova/dariah-campus.git (push)
origin	https://github.com/DARIAH-ERIC/dariah-campus.git (fetch)
origin	https://github.com/DARIAH-ERIC/dariah-campus.git (push)
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git pull upstream master
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git reset --hard b4cf534
HEAD is now at b4cf534 Proofreading WS2019 sessions
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ git remote -v
github-desktop-n-romanova	https://github.com/n-romanova/dariah-campus.git (fetch)
github-desktop-n-romanova	https://github.com/n-romanova/dariah-campus.git (push)
origin	https://github.com/DARIAH-ERIC/dariah-campus.git (fetch)
origin	https://github.com/DARIAH-ERIC/dariah-campus.git (push)
(base) Vickys-MacBook-Pro:dariah-campus vickygarnett$ 
```

I don't know if that causing me a problem?  I have probably pushed or pulled something at the wrong time?

Thanks

V

**Comment by ttasovac** [comment]
Vicky, it looks like you were following Stefan's instructions but from Natasha's pull request branch.

**Comment by ttasovac** [comment]
And that's not where your problem is. Your problem was in the master branch of the main DARIAH-Campus repository (i.e. not your fork).

**Comment by VickyGarnett** [comment]
OK, I'm not sure how that happened, because I made sure I was in the master branch of the main repo.  Settings in GitHub desktop show Current Repo: dariah-campus (the main one), and Current Branch is 'master'.  Was there somewhere else I was supposed to check?

**Comment by ttasovac** [comment]
oh, don't listen to me. i was just guessing. and i guessed wrong. i will shut up before i make things even more complicated...

**Comment by stefanprobst** [comment]
hi vicky,

1. ok, so this is actually *not* happening in your fork (i.e. the repo at https://github.com/VickyGarnett/dariah-campus), but in your local checkout of *this* repo => see question above:

> can you first check that your master branch (i assume we're talking about your fork?) is in sync with upstream?

2. we can ignore the `github-desktop-n-romanova` remote (that seems to have been added by your github GUI)

3. make sure you're in the master branch.

4. since *this* repo is your `origin` remote, you can just `git pull origin master` to fast-forward

5. `git log --oneline | head -n1` should then show "fix: fix compat issue with babel7.8.3+node13" as the last commit in your local checkout.

6. proceed with 6. from [above](https://github.com/DARIAH-ERIC/dariah-campus/issues/48#issuecomment-610435922)

**Comment by VickyGarnett** [comment]
By jove, I think I've got it!!!!

<img width="1280" alt="Screenshot 2020-04-08 at 19 37 36" src="https://user-images.githubusercontent.com/57193002/78820991-a369cd80-79d0-11ea-8982-ebadc0a74233.png">

Thank you Stefan!  Do I need to do this every time now, or can I go back to just the old 'yarn install' and 'yarn develop' as per usual?

**Comment by ttasovac** [comment]
`yarn install ` is done only once to install the packages, you don't have to do it again. 

stefan, many thanks for your help!! what is the difference between `yarn start` and `yarn develop`?

**Comment by stefanprobst** [comment]
@ttasovac 
`yarn start` and `yarn develop` do the exact same thing. while `yarn cache clean` is an internal `yarn` command (see `yarn -h`), you can run any script defined in `package.json` on the `scripts` property with `yarn run scriptname`:
https://github.com/DARIAH-ERIC/dariah-campus/blob/7ab5563a49f7bd525608d816552298dd17fe244c/package.json#L61-L68

while `npm` requires to run these scripts with `npm run scriptname`, `yarn` allows a shorthand version without `run`, e.g. just `yarn scriptname`

**Comment by ttasovac** [comment]
thanks, Stefan!
